/*
 * Copyright (C) 2018 adam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.embeddediq.searchmonkey;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author adam
 */
public class About extends javax.swing.JPanel {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        jLabel1.setToolTipText("http://searchmonkey.embeddediq.com");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jTextPane2.setEditable(false);
        jTextPane2.setContentType("text/html"); // NOI18N
        jTextPane2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jTextPane2.setText("<html><h3>JAVA Searchmonkey v3.1.0</h3> <p>JAVA Searchmonkey is copyright Adam Cottrell <a href=\"mailto:searchmonkey@embededdiq.com?Subject=JAVA Searchmonkey\">searchmonkey@embededdiq.com</a>. Searchmonkey is open source and released under the GPL license</p><br/> <p>For help and support <a href=\"http://searchmonnkey.embeddediq.com/forum\">visit our forum</a>. <a href=\"http://searchmonnkey.embeddediq.com/downloads\">Download the latest Searchmonkey</a></p> </html>");
        jScrollPane3.setViewportView(jTextPane2);

        add(jScrollPane3, java.awt.BorderLayout.SOUTH);

        jLabel2.setText("<html><h1>Welcome!</h1><p><b>JAVA Searchmonkey</b> is a powerful desktop tool for finding files and their content using regular expressions. Searchmonkey combines the power of find/grep and can look inside most text files including PDF, DOCX, XLSX, ODT, and much more besides.</p><br/> <p>To learn more about what Searchmonkey can do for you, then visit our web page: <a href=\"http://searchmonnkey.embeddediq.com\">http://searchmonnkey.embeddediq.com</a></p></html>");
        add(jLabel2, java.awt.BorderLayout.CENTER);
        jLabel2.getAccessibleContext().setAccessibleName("<html><h1>Welcome!</h1><p><b>JAVA Searchmonkey</b> is a powerful desktop tool for finding files and their content using regular expressions. Searchmonkey combines the power of find/grep and can look inside most text files including PDF, DOCX, XLSX, ODT, and much more besides.</p><br/> <p>To learn more about what Searchmonkey can do for you, then visit our web page: <a href=\"http://searchmonnkey.embeddediq.com\">http://searchmonnkey.embeddediq.com</a></p></html>");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://searchmonkey.embeddediq.com"));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(About.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
